# Generated by Django 5.0.1 on 2024-01-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='ult_posicion',
        ),
    ]
