# Generated by Django 5.0.1 on 2024-01-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0002_remove_torneo_ult_posicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadorporequipo',
            old_name='jugador',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='jugadorporequipo',
            old_name='equipo',
            new_name='nombre',
        ),
        migrations.CreateModel(
            name='EquipoPorTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coder.torneo')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coder.equipo')),
            ],
        ),
    ]
